import { jsPDF } from "jspdf";
import { QuizAttempt } from "../types";
import { checkIsAnswerCorrect } from "./answerUtils";

export function generateQuizResultPdf(attempt: QuizAttempt): void {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 16;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const checkPageBreak = (neededHeight: number) => {
    if (y + neededHeight > pageHeight - margin - 10) {
      doc.addPage();
      y = margin;
      drawHeaderBanner(true);
    }
  };

  const drawHeaderBanner = (isContinued = false) => {
    // Top primary bar
    doc.setFillColor(79, 70, 229); // Indigo 600
    doc.rect(margin, y, contentWidth, isContinued ? 8 : 22, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    if (!isContinued) {
      doc.setFontSize(14);
      doc.text("QUIZ PERFORMANCE REPORT", margin + 6, y + 9);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.text("Generated by AI Quiz & Flashcard Study Engine", margin + 6, y + 16);

      const dateStr = new Date(attempt.timestamp).toLocaleDateString("en-US", {
        year: "numeric",
        month: "short",
        day: "numeric",
      });
      doc.setFontSize(9);
      doc.text(dateStr, pageWidth - margin - 6, y + 12, { align: "right" });
      y += 26;
    } else {
      doc.setFontSize(10);
      doc.text("QUIZ PERFORMANCE REPORT (CONTINUED)", margin + 6, y + 5.5);
      y += 12;
    }
  };

  // 1. First Page Header
  drawHeaderBanner(false);

  // 2. Quiz Title & Metadata Card
  doc.setFillColor(248, 250, 252); // Slate 50
  doc.setDrawColor(226, 232, 240); // Slate 200
  doc.roundedRect(margin, y, contentWidth, 22, 2, 2, "FD");

  doc.setTextColor(15, 23, 42); // Slate 900
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  const truncatedTitle = doc.splitTextToSize(attempt.quizTitle, contentWidth - 12);
  doc.text(truncatedTitle[0] || attempt.quizTitle, margin + 6, y + 8);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139); // Slate 500
  const metadataLine = `Subject: ${attempt.subject}  |  Difficulty: ${attempt.difficulty.toUpperCase()}  |  Questions: ${attempt.totalQuestions}  |  Time Spent: ${Math.round(attempt.timeTakenSeconds / 60)}m ${attempt.timeTakenSeconds % 60}s`;
  doc.text(metadataLine, margin + 6, y + 15);

  y += 26;

  // 3. Score Summary Row (4 stat cards)
  const cardGap = 4;
  const cardWidth = (contentWidth - cardGap * 3) / 4;
  const cardHeight = 18;

  // Accuracy Card
  doc.setFillColor(238, 242, 255); // Indigo 50
  doc.setDrawColor(199, 210, 254);
  doc.roundedRect(margin, y, cardWidth, cardHeight, 2, 2, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(79, 70, 229);
  doc.text("ACCURACY", margin + cardWidth / 2, y + 6, { align: "center" });
  doc.setFontSize(12);
  doc.text(`${attempt.percentage}%`, margin + cardWidth / 2, y + 13, { align: "center" });

  // Score Card
  const c2X = margin + cardWidth + cardGap;
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(c2X, y, cardWidth, cardHeight, 2, 2, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("TOTAL SCORE", c2X + cardWidth / 2, y + 6, { align: "center" });
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text(`${attempt.score} / ${attempt.totalQuestions}`, c2X + cardWidth / 2, y + 13, { align: "center" });

  // Correct Card
  const c3X = c2X + cardWidth + cardGap;
  doc.setFillColor(236, 253, 245); // Emerald 50
  doc.setDrawColor(167, 243, 208);
  doc.roundedRect(c3X, y, cardWidth, cardHeight, 2, 2, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(5, 150, 105);
  doc.text("CORRECT", c3X + cardWidth / 2, y + 6, { align: "center" });
  doc.setFontSize(12);
  doc.text(`${attempt.correctCount}`, c3X + cardWidth / 2, y + 13, { align: "center" });

  // Incorrect / Skipped Card
  const c4X = c3X + cardWidth + cardGap;
  doc.setFillColor(254, 242, 242); // Rose 50
  doc.setDrawColor(254, 202, 202);
  doc.roundedRect(c4X, y, cardWidth, cardHeight, 2, 2, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(225, 29, 72);
  doc.text("INCORRECT / SKIP", c4X + cardWidth / 2, y + 6, { align: "center" });
  doc.setFontSize(12);
  doc.text(`${attempt.incorrectCount} / ${attempt.skippedCount}`, c4X + cardWidth / 2, y + 13, { align: "center" });

  y += cardHeight + 7;

  // 4. Topic Breakdown (if available)
  if (attempt.topicPerformance && Object.keys(attempt.topicPerformance).length > 0) {
    checkPageBreak(25);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    doc.text("Topic-Wise Performance Breakdown", margin, y);
    y += 4;

    const topics = Object.entries(attempt.topicPerformance);
    for (const [topic, val] of topics) {
      const data = val as { total: number; correct: number };
      const pct = Math.round((data.correct / (data.total || 1)) * 100);
      checkPageBreak(12);

      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(241, 245, 249);
      doc.roundedRect(margin, y, contentWidth, 8, 1, 1, "FD");

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(51, 65, 85);
      doc.text(topic, margin + 4, y + 5.5);

      doc.setFont("helvetica", "bold");
      const statTxt = `${data.correct}/${data.total} correct (${pct}%)`;
      if (pct >= 80) doc.setTextColor(5, 150, 105);
      else if (pct >= 50) doc.setTextColor(217, 119, 6);
      else doc.setTextColor(225, 29, 72);

      doc.text(statTxt, pageWidth - margin - 4, y + 5.5, { align: "right" });
      y += 9.5;
    }
    y += 4;
  }

  // 5. Questions and Explanations Review Section Header
  checkPageBreak(15);
  doc.setFillColor(241, 245, 249);
  doc.rect(margin, y, contentWidth, 7, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.setTextColor(30, 41, 59);
  doc.text("QUESTION BY QUESTION REVIEW & DETAILED EXPLANATIONS", margin + 4, y + 5);
  y += 10;

  // 6. Iterate through each question
  attempt.questions.forEach((q, index) => {
    const userAns = attempt.userAnswers[q.id];
    const isSkipped = !userAns || String(userAns).trim() === "";
    const isCorrect = !isSkipped && checkIsAnswerCorrect(userAns, q.correctAnswer);

    // Prepare text lines to measure required height
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    const qLines: string[] = doc.splitTextToSize(
      `${index + 1}. ${q.question}`,
      contentWidth - 10
    );

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    const userAnsLine = `Your Answer: ${isSkipped ? "[Skipped - No answer given]" : userAns}`;
    const correctAnsLine = `Correct Answer: ${q.correctAnswer}`;

    const expLines: string[] = doc.splitTextToSize(
      `Explanation: ${q.explanation}`,
      contentWidth - 14
    );

    // Approximate height calculation:
    // Header tag (6mm) + question text (qLines.length * 4) + answers (9mm) + explanation (expLines.length * 3.8 + 4) + padding (8)
    const blockHeight = 6 + qLines.length * 4.2 + 10 + expLines.length * 3.8 + 8;
    checkPageBreak(Math.min(blockHeight, 70));

    // Card background
    if (isCorrect) {
      doc.setFillColor(240, 253, 244); // light green
      doc.setDrawColor(187, 247, 208);
    } else if (isSkipped) {
      doc.setFillColor(254, 252, 232); // light amber
      doc.setDrawColor(254, 240, 138);
    } else {
      doc.setFillColor(254, 242, 242); // light red
      doc.setDrawColor(254, 202, 202);
    }

    const cardStartY = y;
    doc.roundedRect(margin, cardStartY, contentWidth, blockHeight, 2, 2, "FD");

    // Question Status Pill
    y += 5;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    if (isCorrect) {
      doc.setTextColor(21, 128, 61);
      doc.text(`CORRECT  •  ${q.type.toUpperCase()}${q.topic ? `  •  ${q.topic}` : ""}`, margin + 5, y);
    } else if (isSkipped) {
      doc.setTextColor(180, 83, 9);
      doc.text(`SKIPPED  •  ${q.type.toUpperCase()}${q.topic ? `  •  ${q.topic}` : ""}`, margin + 5, y);
    } else {
      doc.setTextColor(185, 28, 28);
      doc.text(`INCORRECT  •  ${q.type.toUpperCase()}${q.topic ? `  •  ${q.topic}` : ""}`, margin + 5, y);
    }

    // Question text
    y += 4.5;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(15, 23, 42);
    doc.text(qLines, margin + 5, y);
    y += qLines.length * 4.2 + 2;

    // User Answer
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    if (isCorrect) doc.setTextColor(21, 128, 61);
    else if (isSkipped) doc.setTextColor(180, 83, 9);
    else doc.setTextColor(185, 28, 28);
    doc.text(userAnsLine, margin + 5, y);
    y += 4.5;

    // Correct Answer
    doc.setFont("helvetica", "bold");
    doc.setTextColor(22, 101, 52);
    doc.text(correctAnsLine, margin + 5, y);
    y += 5.5;

    // Explanation Box
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(226, 232, 240);
    const expBoxHeight = expLines.length * 3.8 + 4;
    doc.roundedRect(margin + 4, y - 2, contentWidth - 8, expBoxHeight, 1.5, 1.5, "FD");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    doc.text(expLines, margin + 7, y + 2);

    y = cardStartY + blockHeight + 4;
  });

  // 7. Add page numbers at bottom footer for all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // Slate 400
    doc.text(
      `Quiz Master AI  •  Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 6,
      { align: "center" }
    );
  }

  // Save the PDF file
  const sanitizedTitle = attempt.quizTitle.replace(/[^a-zA-Z0-9_-]/g, "_").toLowerCase();
  const filename = `${sanitizedTitle || "quiz"}_results_report.pdf`;
  doc.save(filename);
}
